// GENERATED by src/spec/genEventLayouts.ts from the contract binaries.
// Do not edit: run `npm run gen:events` after rebuilding the contracts.
//
// Each entry is one `#[contractevent]` as its contract's spec declares it:
// the data format and every parameter, in order, with whether it travels
// as a topic or in the data. events.ts decodes by these layouts and types
// its results from them, so a field the contracts add, remove or reorder
// changes the decoder and its types on the next `gen:events` instead of
// silently shifting every column after it.

export const EVENT_LAYOUTS = {
    /** From target/wasm32v1-none/release/factory.wasm. */
    factory: {
        // ContractUpgraded
        contract_upgraded: {
            format: "map",
            params: [
                { name: "new_wasm_hash", in: "data", type: "bytes" },
            ],
        },

        // FeeConfigUpdated
        fee_config_updated: {
            format: "map",
            params: [
                { name: "old_config", in: "data", type: "udt:FeeConfig" },
                { name: "new_config", in: "data", type: "udt:FeeConfig" },
            ],
        },

        // MarketCreated
        market_created: {
            format: "single",
            params: [
                { name: "creator", in: "topic", type: "address" },
                { name: "vault", in: "topic", type: "address" },
                { name: "market", in: "data", type: "udt:Market" },
            ],
        },

        // OwnershipRenounced
        ownership_renounced: {
            format: "map",
            params: [
                { name: "old_owner", in: "data", type: "address" },
            ],
        },

        // OwnershipTransfer
        ownership_transfer: {
            format: "map",
            params: [
                { name: "old_owner", in: "data", type: "address" },
                { name: "new_owner", in: "data", type: "address" },
                { name: "live_until_ledger", in: "data", type: "u32" },
            ],
        },

        // OwnershipTransferCompleted
        ownership_transfer_completed: {
            format: "map",
            params: [
                { name: "new_owner", in: "data", type: "address" },
            ],
        },

        // WasmHashesUpdated
        wasm_hashes_updated: {
            format: "map",
            params: [
                { name: "old_hashes", in: "data", type: "udt:WasmHashes" },
                { name: "new_hashes", in: "data", type: "udt:WasmHashes" },
            ],
        },
    },
    /** From target/wasm32v1-none/release/yield_manager.wasm. */
    ym: {
        // Deposit
        deposit: {
            format: "vec",
            params: [
                { name: "from", in: "topic", type: "address" },
                { name: "shares_amount", in: "data", type: "i128" },
                { name: "mint_amount", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // DepositAsset
        deposit_asset: {
            format: "vec",
            params: [
                { name: "from", in: "topic", type: "address" },
                { name: "asset_in", in: "data", type: "i128" },
                { name: "shares_in", in: "data", type: "i128" },
                { name: "mint_amount", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // DistributeYield
        distribute_yield: {
            format: "vec",
            params: [
                { name: "to", in: "topic", type: "address" },
                { name: "shares_amount", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // FlashDeposit
        flash_deposit: {
            format: "vec",
            params: [
                { name: "user", in: "topic", type: "address" },
                { name: "amm", in: "topic", type: "address" },
                { name: "yt_out", in: "data", type: "i128" },
                { name: "v_to_mint", in: "data", type: "i128" },
                { name: "user_cost", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // FlashRedeem
        flash_redeem: {
            format: "vec",
            params: [
                { name: "user", in: "topic", type: "address" },
                { name: "amm", in: "topic", type: "address" },
                { name: "pt_borrowed", in: "data", type: "i128" },
                { name: "v_owed", in: "data", type: "i128" },
                { name: "v_to_user", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // PoolSet
        pool_set: {
            format: "map",
            params: [
                { name: "pool", in: "topic", type: "address" },
            ],
        },

        // RedeemCombined
        redeem_combined: {
            format: "vec",
            params: [
                { name: "from", in: "topic", type: "address" },
                { name: "amount", in: "data", type: "i128" },
                { name: "shares_returned", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // RedeemPrincipal
        redeem_principal: {
            format: "vec",
            params: [
                { name: "from", in: "topic", type: "address" },
                { name: "pt_amount", in: "data", type: "i128" },
                { name: "shares_returned", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // RedeemToAsset
        redeem_to_asset: {
            format: "vec",
            params: [
                { name: "from", in: "topic", type: "address" },
                { name: "burned", in: "data", type: "i128" },
                { name: "shares_redeemed", in: "data", type: "i128" },
                { name: "asset_out", in: "data", type: "i128" },
                { name: "exchange_rate", in: "data", type: "i128" },
            ],
        },

        // SurplusCollected
        surplus_collected: {
            format: "vec",
            params: [
                { name: "treasury", in: "topic", type: "address" },
                { name: "amount", in: "data", type: "i128" },
            ],
        },

        // TokenContractsSet
        token_contracts_set: {
            format: "map",
            params: [
                { name: "pt", in: "topic", type: "address" },
                { name: "yt", in: "topic", type: "address" },
            ],
        },
    },
    /** From target/wasm32v1-none/release/amm.wasm. */
    amm: {
        // Deposit
        deposit: {
            format: "vec",
            params: [
                { name: "to", in: "topic", type: "address" },
                { name: "amount_a", in: "data", type: "i128" },
                { name: "amount_b", in: "data", type: "i128" },
                { name: "shares_minted", in: "data", type: "i128" },
                { name: "new_reserve_a", in: "data", type: "i128" },
                { name: "new_reserve_b", in: "data", type: "i128" },
            ],
        },

        // FlashSwapPt
        flash_swap_pt: {
            format: "vec",
            params: [
                { name: "receiver", in: "topic", type: "address" },
                { name: "user", in: "topic", type: "address" },
                { name: "pt_bought", in: "data", type: "i128" },
                { name: "v_paid", in: "data", type: "i128" },
                { name: "new_implied_rate", in: "data", type: "i128" },
                { name: "new_reserve_a", in: "data", type: "i128" },
                { name: "new_reserve_b", in: "data", type: "i128" },
                { name: "fee", in: "data", type: "i128" },
                { name: "reserve_fee", in: "data", type: "i128" },
            ],
        },

        // FlashSwapV
        flash_swap_v: {
            format: "vec",
            params: [
                { name: "receiver", in: "topic", type: "address" },
                { name: "user", in: "topic", type: "address" },
                { name: "pt_borrowed", in: "data", type: "i128" },
                { name: "v_owed", in: "data", type: "i128" },
                { name: "new_implied_rate", in: "data", type: "i128" },
                { name: "new_reserve_a", in: "data", type: "i128" },
                { name: "new_reserve_b", in: "data", type: "i128" },
                { name: "fee", in: "data", type: "i128" },
                { name: "reserve_fee", in: "data", type: "i128" },
            ],
        },

        // PoolInit
        pool_init: {
            format: "map",
            params: [
                { name: "token_a", in: "topic", type: "address" },
                { name: "token_b", in: "topic", type: "address" },
                { name: "expiry_ts", in: "data", type: "u64" },
                { name: "current_apy", in: "data", type: "i128" },
                { name: "apy_min", in: "data", type: "i128" },
                { name: "apy_max", in: "data", type: "i128" },
                { name: "fee_apy", in: "data", type: "i128" },
                { name: "scalar_root", in: "data", type: "i128" },
                { name: "fee_rate_root", in: "data", type: "i128" },
                { name: "last_implied_rate", in: "data", type: "i128" },
                { name: "treasury", in: "data", type: "address" },
                { name: "reserve_fee_rate", in: "data", type: "i128" },
            ],
        },

        // ReserveFeePaid
        reserve_fee_paid: {
            format: "vec",
            params: [
                { name: "treasury", in: "topic", type: "address" },
                { name: "amount", in: "data", type: "i128" },
            ],
        },

        // SwapPtForV
        swap_pt_for_v: {
            format: "vec",
            params: [
                { name: "to", in: "topic", type: "address" },
                { name: "pt_in", in: "data", type: "i128" },
                { name: "v_out", in: "data", type: "i128" },
                { name: "new_implied_rate", in: "data", type: "i128" },
                { name: "new_reserve_a", in: "data", type: "i128" },
                { name: "new_reserve_b", in: "data", type: "i128" },
                { name: "fee", in: "data", type: "i128" },
                { name: "reserve_fee", in: "data", type: "i128" },
            ],
        },

        // SwapVForPt
        swap_v_for_pt: {
            format: "vec",
            params: [
                { name: "to", in: "topic", type: "address" },
                { name: "v_in", in: "data", type: "i128" },
                { name: "pt_out", in: "data", type: "i128" },
                { name: "new_implied_rate", in: "data", type: "i128" },
                { name: "new_reserve_a", in: "data", type: "i128" },
                { name: "new_reserve_b", in: "data", type: "i128" },
                { name: "fee", in: "data", type: "i128" },
                { name: "reserve_fee", in: "data", type: "i128" },
            ],
        },

        // Withdraw
        withdraw: {
            format: "vec",
            params: [
                { name: "to", in: "topic", type: "address" },
                { name: "share_amount", in: "data", type: "i128" },
                { name: "amount_a", in: "data", type: "i128" },
                { name: "amount_b", in: "data", type: "i128" },
                { name: "new_reserve_a", in: "data", type: "i128" },
                { name: "new_reserve_b", in: "data", type: "i128" },
            ],
        },
    },
    /** From target/wasm32v1-none/release/router.wasm. */
    router: {
        // ExitedExpired
        exit_expired: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "lp_shares", in: "data", type: "i128" },
                { name: "pt_redeemed", in: "data", type: "i128" },
                { name: "shares_out", in: "data", type: "i128" },
            ],
        },

        // ExitedExpiredToAsset
        exit_expired_to_asset: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "lp_shares", in: "data", type: "i128" },
                { name: "asset_out", in: "data", type: "i128" },
            ],
        },

        // SwapVForYt
        swap_v_for_yt: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "v_in", in: "data", type: "i128" },
                { name: "yt_out", in: "data", type: "i128" },
            ],
        },

        // SwapYtForV
        swap_yt_for_v: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "yt_in", in: "data", type: "i128" },
                { name: "v_out", in: "data", type: "i128" },
            ],
        },

        // ZapAssetForLp
        zap_asset_for_lp: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "asset_in", in: "data", type: "i128" },
                { name: "pt_bought", in: "data", type: "i128" },
                { name: "lp_out", in: "data", type: "i128" },
            ],
        },

        // ZapAssetForPt
        zap_asset_for_pt: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "asset_in", in: "data", type: "i128" },
                { name: "pt_out", in: "data", type: "i128" },
            ],
        },

        // ZapAssetForSplit
        zap_asset_for_split: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "asset_in", in: "data", type: "i128" },
                { name: "tokens_out", in: "data", type: "i128" },
            ],
        },

        // ZapAssetForYt
        zap_asset_for_yt: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "asset_in", in: "data", type: "i128" },
                { name: "yt_out", in: "data", type: "i128" },
            ],
        },

        // ZapLpForAsset
        zap_lp_for_asset: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "lp_in", in: "data", type: "i128" },
                { name: "pt_sold", in: "data", type: "i128" },
                { name: "asset_out", in: "data", type: "i128" },
            ],
        },

        // ZapPtForAsset
        zap_pt_for_asset: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "pt_in", in: "data", type: "i128" },
                { name: "asset_out", in: "data", type: "i128" },
            ],
        },

        // ZapSplitForAsset
        zap_split_for_asset: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "tokens_in", in: "data", type: "i128" },
                { name: "asset_out", in: "data", type: "i128" },
            ],
        },

        // ZapYtForAsset
        zap_yt_for_asset: {
            format: "vec",
            params: [
                { name: "vault", in: "topic", type: "address" },
                { name: "to", in: "topic", type: "address" },
                { name: "maturity", in: "data", type: "u64" },
                { name: "asset", in: "data", type: "address" },
                { name: "yt_in", in: "data", type: "i128" },
                { name: "asset_out", in: "data", type: "i128" },
            ],
        },
    },
} as const;
